brakeman:
  comment: true
  exit_code: 0
  ignore: false
bundle-audit:
  comment: true
  exit_code: 0
  ignore: false
eslint:
  comment: true
  exit_code: 256
  ignore: false
rails_best_practices:
  comment: true
  exit_code: 256
  ignore: false
reek:
  comment: true
  exit_code: 512
  ignore: false
rspec:
  comment: true
  exit_code: 256
  ignore: false
rubocop:
  comment: true
  exit_code: 256
  ignore: false
scss-lint:
  comment: true
  exit_code: 256
  ignore: false
